name: emoji_exp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.2.0
  location: ^5.0.0
  animations: ^2.0.11
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^12.0.0+1
  vibration: ^3.1.3
  vector_math: ^2.1.4
  intl: ^0.20.2
  geocoding: ^3.0.0
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.15
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/emoji.png
    - assets/still.png
    - assets/walking.png
    - assets/stars_bg.png
